INSERT INTO ITEMS (NAME, PRICE, IMPORTED, EXEMPT, ACTIVE) VALUES('book', 12.49, 0, 1, 1);
INSERT INTO ITEMS (NAME, PRICE, IMPORTED, EXEMPT, ACTIVE) VALUES('music CD', 14.99, 0, 0, 1);
INSERT INTO ITEMS (NAME, PRICE, IMPORTED, EXEMPT, ACTIVE) VALUES('chocolate bar', 0.85, 0, 1, 1);
INSERT INTO ITEMS (NAME, PRICE, IMPORTED, EXEMPT, ACTIVE) VALUES('imported box of chocolates', 10.00, 1, 1, 1);
INSERT INTO ITEMS (NAME, PRICE, IMPORTED, EXEMPT, ACTIVE) VALUES('imported bottle of perfume', 47.50, 1, 0, 1);
INSERT INTO ITEMS (NAME, PRICE, IMPORTED, EXEMPT, ACTIVE) VALUES('imported bottle of perfume', 27.99, 1, 0, 1);
INSERT INTO ITEMS (NAME, PRICE, IMPORTED, EXEMPT, ACTIVE) VALUES('bottle of perfume', 18.99, 0, 0, 1);
INSERT INTO ITEMS (NAME, PRICE, IMPORTED, EXEMPT, ACTIVE) VALUES('packet of headache pills', 9.75, 0, 1, 1);
INSERT INTO ITEMS (NAME, PRICE, IMPORTED, EXEMPT, ACTIVE) VALUES('box of imported chocolates', 11.25, 1, 1, 1);

